name = "difas-reservas-mantenimiento"
main = "src/index.js"
compatibility_date = "2026-04-27"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "difas-bautismo-mar"
database_id = "7e12be39-94aa-4236-ab0a-fab3d3e74a7a"
